services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER=true
    ports:
      - "7000:7000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"