global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets: ['event-service:5000', 'team-service:5001', 'player-service:5002', 'stats-service:5003',
                  'flight-service:5004', 'origin-service:5005', 'destination-service:5006', 'airline-service:5007']
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:4000']